### ISSUE TITLE
Some UI elements mask the time slider

### ISSUE THREAD

**Issue by ozls** [xou816/spot#192] opened 2021-04-13 16:35 UTC
**Describe the bug**
This is a small glitch that has very little impact, but I like Spot so if I can do somehting to help improve.. I noticed some UI elements mask the time slider and the moving dot appears halved (see screenshot). Such UI elements include album/playlist thumbnails or the whole "Now playing" menu

**To Reproduce**
1. Play a song
2. Watch time slider closely
 
**Expected behavior**
Time slider is on top

**Screenshots**
![2021-04-13_18-04-1618331346](https://user-images.githubusercontent.com/34961309/114587676-6ab0a400-9c75-11eb-84a6-a106d23ddb49.jpg)

**General information:**
 - Distribution: Arch (with Sway WM)
 - Installation method [e. g. built from source, installed from Flathub...]: AUR
 - Version: 0.1.13
 - Device used: Desktop

**Comment by xou816** [comment] 2021-04-13 17:17
Duplicate of #165 closing if you don't mind ;)

**Closed by xou816** 2021-04-13 17:17 UTC
Labels: bug
