### ISSUE TITLE
Crashes on login

### ISSUE THREAD

**Issue by estebanjosealva** [xou816/spot#21] opened 2021-01-15 17:29 UTC
Hi there! I installed Spot via Flatpak, but every time I try to login it crashes and closes.

Here's my system info:

Linux ubuntu-spectre 5.8.0-38-generic #43-Ubuntu SMP Tue Jan 12 12:42:13 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Please let me know if you need any other details. Regards.

**Comment by xou816** [comment] 2021-01-15 22:28
Hi! 
Sorry for the poor experience with spot, I should really make it clear it is alpha quality software at best... 
Do you have a premium account or is it a free one? Only the former is supported (but it should ideally not crash with a free account).
If possible, would you be able to run spot from the command line to check for any helpful output?
`$ flatpak run dev.alextren.Spot`
Thank you for trying out the app and for your report :)

**Comment by estebanjosealva** [comment] 2021-01-15 23:13
Hi there, thanks for your quick reply!

I do have a premium account. Running it using the command above helped and I was able to log in. Couple things I noticed:

- Volume control does not do anything. I'm playing via bluetooth.
- Would it be possible to include the option to show playlists?
- Option for shuffle play?

Other than that, everything seems to work fine. I, for one, really appreciate your efforts. If I was more knowledgeable I would have helped you a bit more...

**Comment by xou816** [comment] 2021-01-16 18:00
Hi again :) 

I am glad it helped, although frankly I don't know why it would, I'll have to investigate to understand the crash!

I'll keep this issue open in case other people come across the crash and have additional info.

---

As for your other questions:
- I have that warning as well, I don't know how to expose that module to the Flatpak sandbox, but it's not useful to the app so you can safely ignore it :)
- oh uh... I have not implemented it, sorry :D there are a couple other controls in the app that don't do anything yet
- absolutely, I have a long list of things I'd like to work on, and playlists are one of these! 
- same answer, planned, just need to find the time to work on that :)

One thing I could do is list those features as individual issues so users like you can have a better overview of the progress, I'll see what I can do (lots of promises, I know... !)

Thank you for the nice words, it's definitely helping with motivation :)

**Comment by g7** [comment] 2021-01-17 15:19
Hi,

I chime in to say that I had the same problem as OP, and I found that it happens due to keychain not being unlocked (this was on a mobile phone running mobian, on gnome at least the keychain is unlocked on login). Unlocking the keychain via another app (for example FeedReader, or seahorse would work too) made it work.

Thanks for this application, looks very promising and already works fine!

**Comment by xou816** [comment] 2021-01-17 17:58
Hi!
Thank you for your help! I could reproduce a crash related to the keychain being locked indeed! I don't know if it is the same issue estebanjosealva encountered, but that might be it!
It will be fixed in the next version, error management on login is pretty messy atm but at least it should no longer crash :D 
Thank you very much for your feedback as well!

**Closed** 2021-01-21 22:02 UTC
