### ISSUE TITLE
(Enchacement) Library or playlist should display the Liked Songs playlist

### ISSUE THREAD

**Issue by Barraguesh** [xou816/spot#100] opened 2021-02-24 19:18 UTC
Liked song playlist is nowhere to be seen. I can see my liked full albums in the library but that's it. I mainly used liked songs so I was surprised to not to have the option.

**Comment by xou816** [comment] 2021-02-24 21:04
Duplicate of #51 ;) but thank you for your interest! I agree this is needed

**Closed by xou816** 2021-02-24 21:04 UTC

**Comment by Barraguesh** [comment] 2021-02-26 09:07
Sorry I searched with "Liked songs" and didn't find anything...

**Comment by xou816** [comment] 2021-02-26 09:08
No worries, I'll actually update the other issue to use your title, it's a bit clearer!
