### ISSUE TITLE
[Feature request] Discord Presence

### ISSUE THREAD

**Issue by CleoMenezes** [xou816/spot#310] opened 2021-09-12 16:01 UTC
![image](https://user-images.githubusercontent.com/54215258/132994530-374c2401-40ba-49f4-88f9-f3edd62d5490.png)

Is there any way to show what I'm listening to on Discord? It would be a great feature.

**Comment by xou816** [comment] 2021-09-12 16:31
Duplicate of #101

**Closed by xou816** 2021-09-12 16:31 UTC
