### ISSUE TITLE
Visual glitches that affect core functions of the app.

### ISSUE THREAD

**Issue by the-cave-dweller** [xou816/spot#545] opened 2022-08-24 19:10 UTC
**Describe the bug**
Visual glitches on small screens, while searching or scrolling individual playlists, this is not happening on library overviews and playlists inside them, those seem to work fine.
**To Reproduce**
Using a small screen with UI scaling applied, currently affecting pinephone.

**Expected behavior**
Being able to access playlist and search functions, like on the "library" and "all playlist" overview

https://user-images.githubusercontent.com/53988947/186502102-93aaa5aa-30f4-4cb3-a25f-b2a0d295c572.mp4

**General information:**
Archlinux ARM, on both flatpak and native build.

Console output:
`(process:19270): Adwaita-CRITICAL **: 14:30:29.581: adw_leaflet_set_visible_child: assertion 'contains_child' failed
`

**Comment by the-cave-dweller** [comment] 2022-08-24 19:45
Scaling the app to show all of its elements makes it work normally, it just happens when the elements are in a compact view.

**Comment by XGZepto** [comment] 2023-02-16 11:42
Duplicate of #521

**Comment by xou816** [comment] 2023-02-18 16:57
closing as duplicate, thanks XGZepto, moving discussion over there

**Closed by xou816** 2023-02-18 16:57 UTC
Labels: bug
