### ISSUE TITLE
Can't Login no error display

### ISSUE THREAD

**Issue by Thijzer** [xou816/spot#26] opened 2021-01-21 23:14 UTC
Tried your app but I can't login, with 0.1.1 flatpak.

**Comment by xou816** [comment] 2021-01-22 07:09
Hi! Thank you for your report. Could you run Spot from the command line and share any relevant output?
`$ flatpak run dev.alextren.Spot`

(btw, I am waiting for an upstream change to properly handle login failures, so it should hopefully get better soon!)

**Comment by lightonflux** [comment] 2021-01-25 09:06
```
flatpak run dev.alextren.Spot                                              1 ↵
Gtk-Message: 10:02:51.967: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:02:51.969: Failed to load module "pk-gtk-module"
Gtk-Message: 10:02:51.971: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:02:51.971: Failed to load module "pk-gtk-module"
home
thread '<unnamed>' panicked at 'Authentication failed with reason: BadCredentials', /run/build/spot/cargo/vendor/librespot-core-0.1.3/src/connection/mod.rs:121:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

I double checked the password, it is correct.

**Comment by xou816** [comment] 2021-01-25 10:54
Hmm, that's weird! Is there anything special about your username/password (that you feel comfortable to share)?
Also, have you tried with both email and username? (both should work IIRC)
Thanks for the additional report in any case!

**Comment by lightonflux** [comment] 2021-01-25 11:04
The Usename has a dash "-" in the name "like `abc-def`. Password doesn't even have special chars. I even changed the PW to only [a-z][A-Z], in case there was an escaping error. But no, that didn't change anything.

**Comment by xou816** [comment] 2021-01-25 12:34
Thank you for going as far as to changed your password! :o I am clueless as to what might be happening here :/ I'll try debugging later to see if the dash might be removed for some reason when authenticating, but I don't see why it would! Please tell me if you have any luck with the email :)

**Comment by lightonflux** [comment] 2021-01-25 15:20
Used my email and it worked. But then i logged out. And now it looks like the login window is above the logged in user. Because the UI didn't update. Which doesn't feel like i was successfully logged out. 

![Bildschirmfoto von 2021-01-25 16-17-18](https://user-images.githubusercontent.com/1377943/105725088-d31a9f80-5f28-11eb-98ad-c600903bfc2a.png)

So i tried to login again. First with name only. Same error as above. Then i changed to email. But this does not work. Without error. 

So i had to restart the application and try the email immediately. I guess the dialogue breaks if the library throws an error.

**Comment by xou816** [comment] 2021-01-25 15:35
Great news :) still weird that it wouldn't work with the username, but then again Spotify usernames are funky (some are only display names)

Indeed, the cache is not cleared after a log out, it might be less confusing to clear it indeed. I'll give it some thought, thnks for the feedback!

As for the issue with attempting to log in after an error: you're absolutely right, the thread that handles playing/authentication crashes after a failed attempt and a restart is required. I'm waiting for a change in an upstream project to be able to handle login failures more gracefully!

**Comment by Diegovsky** [comment] 2023-02-26 14:23
@Thijzer does this still apply in the latest version?

**Comment by lightonflux** [comment] 2023-02-27 00:42
I am not subscribed to Spotify currently, so I think I cannot test it.

**Comment by lightonflux** [comment] 2023-02-27 00:45
Just tried it with my email as user. And i can login on the web, but not in spot. But as i sad i don't have Spotify Premium.

**Comment by Diegovsky** [comment] 2023-02-27 16:51
Spot does not work with free accounts though. Closing this issue as it can't be reproduced but feel free to re-open if you manage to

**Closed by Diegovsky** 2023-02-27 16:51 UTC
Labels: bug, question
