### ISSUE TITLE
Playback continues when application window is closed

### ISSUE THREAD

**Issue by daPhipz** [xou816/spot#151] opened 2021-03-16 01:47 UTC
When a song is playing and I close the window, the music keeps on playing. I have to stop it via the notification in GNOME Shell.

**To Reproduce**
1. Start playing any song.
2. Close `spot` by clicking the `X` window button.
3. The music keeps on playing.

**Expected behavior**
The music should have stopped when closing `spot`.

**General information:**
 - Distribution: Ubuntu 20.10
 - Installation method: snap
 - Version: 0.1.9
 - Device used: Laptop (Acer Aspire something)

**Comment by exciteabletom** [comment] 2021-03-16 02:05
Duplicate of #132?

**Comment by daPhipz** [comment] 2021-03-16 02:15
No, not really - I don't get the popup which warns about `spot` running in the background, It just keeps playing music. As I see it, they did not play any music - see the **To Reproduce** section of #132.

But reading the reply to the bug report you mentioned, I think this is by design. Not good design, imo...
When I close an application by clicking the X on the window, I want it to be terminated completely. If I want it to run in the background, I would simply minimize it.

**Comment by xou816** [comment] 2021-03-16 08:30
Oh, I guess snap allows background execution unconditionally!

But yeah, this is by design; I'm targeting the GNOME desktop and HIG, where there is no minimize behavior. Instead, windows are closed (not apps). There are several ways to quit the app (GNOME shell's menu item, "Quit" from Spot menu, Ctrl Q, and finally pausing playback before closing the window).

**Comment by daPhipz** [comment] 2021-03-16 08:59
Ah ok I see... I am so used to have a minimize button on GNOME that I considered it standard xD
In that case, I can see why you decided to design it like this. I will have to adapt my way of doing things then ;)

Thanks for the quick reply!

**Closed** 2021-03-16 08:59 UTC
Labels: bug
