### ISSUE TITLE
Unable to play podcasts.

### ISSUE THREAD

**Issue by CleoMenezes** [xou816/spot#300] opened 2021-09-05 03:38 UTC
**Describe the bug**
Can't play podcasts.

**To Reproduce**

1.  Create/add a playlist with podcasts episodes.
2. Try to play it.

![Kooha-2021-09-04-23_33_31](https://user-images.githubusercontent.com/54215258/132114123-e5130460-7992-498d-86a1-bf99bb324ddf.gif)

**Comment by ondras12345** [comment] 2021-09-05 07:50
Duplicate of https://github.com/xou816/spot/issues/95

**Comment by xou816** [comment] 2021-09-05 10:17
Thank you ondras, really appreciate that you help me sort through issues and questions :)

**Closed by xou816** 2021-09-05 10:17 UTC
Labels: bug
