### ISSUE TITLE
Crash when minimizing window

### ISSUE THREAD

**Issue by celldra** [xou816/spot#632] opened 2023-03-10 11:11 UTC
**Describe the bug**
The application hangs and crashes with a coredump message in the syslog after I attempted to play a song and minimized the application. I'm unsure if the bug is directly caused by the minimize operation or by something else.

**To Reproduce**
1. Open a playlist
2. Scroll to the bottom
3. Play a song
4. Immediately try and minimize the application

**Expected behavior**
The window to minimize and the music to continue playing

**General information:**
 - Distribution: Arch
 - Installation method: Built from source
 - Version: 0.4.0
 - Device used: Desktop

**Stack trace:**
```
Process 152690 (spot) of user 1000 dumped core.

Stack trace of thread 152690:
#0  0x00007f1c90aa08ec n/a (libc.so.6 + 0x878ec)
#1  0x00007f1c90a51ea8 raise (libc.so.6 + 0x38ea8)
#2  0x00007f1c90a3b53d abort (libc.so.6 + 0x2253d)
#3  0x00007f1c912cc06a n/a (libglib-2.0.so.0 + 0x1d06a)
#4  0x00007f1c91327a90 g_assertion_message_expr (libglib-2.0.so.0 + 0x78a90)
#5  0x00007f1c91974ef8 n/a (libgtk-4.so.1 + 0x174ef8)
#6  0x00007f1c919753e7 n/a (libgtk-4.so.1 + 0x1753e7)
#7  0x00007f1c91402210 g_closure_invoke (libgobject-2.0.so.0 + 0x14210)
#8  0x00007f1c9142feb8 n/a (libgobject-2.0.so.0 + 0x41eb8)
#9  0x00007f1c9141ff85 g_signal_emit_valist (libgobject-2.0.so.0 + 0x31f85)
#10 0x00007f1c91420214 g_signal_emit (libgobject-2.0.so.0 + 0x32214)
#11 0x00007f1c91986ea8 n/a (libgtk-4.so.1 + 0x186ea8)
#12 0x00007f1c91402210 g_closure_invoke (libgobject-2.0.so.0 + 0x14210)
#13 0x00007f1c9142feb8 n/a (libgobject-2.0.so.0 + 0x41eb8)
#14 0x00007f1c9141ff85 g_signal_emit_valist (libgobject-2.0.so.0 + 0x31f85)
#15 0x00007f1c91420214 g_signal_emit (libgobject-2.0.so.0 + 0x32214)
#16 0x0000557a5b079cda n/a (/home/user/.local/bin/spot + 0x50ecda)
ELF object binary architecture: AMD x86-64
```

**Additional context**
I did not use the v0.4.0 release, I cloned the repository to include the latest dependabot commit from last week.

**Comment by xou816** [comment] 2023-03-10 18:07
Hi! Hmm, I have not been able to reproduce it (using arch ~as well~ btw). Looks like a crash in Gtk or libc. 
Have you had updates recently or are you using unstable versions of either of these? Have you noticed issues with other Gtk apps? What about the flatpak version if you're able to test?

**Comment by celldra** [comment] 2023-03-10 19:52
Hey!

I don't believe I'm using any development versions of any packages, and it could be worth mentioning that I'm running it on GNOME 43.3 on kernel version 6.1.15-1 and built with Cargo 1.67.1

It could potentially be something do to with the fact that I'm using a custom patched Mutter build which is available on [AUR](https://aur.archlinux.org/packages/mutter-x11-scaling).

**Comment by xou816** [comment] 2023-03-18 23:49
I hope you won't mind me closing this as it is likely not related to spot
feel free to reopen if you're able to reproduce with a stable Mutter build or if you have a good reason to believe it is related to spot

**Closed as completed by xou816** 2023-03-18 23:49 UTC
Labels: bug
