### ISSUE TITLE
[Flatpak][Wayland] GTK theme is not being used

### ISSUE THREAD

**Issue by teohhanhui** [xou816/spot#99] opened 2021-02-24 17:22 UTC
**Describe the bug**
When installed from Flatpak and running on Wayland, GTK theme (Matcha-sea) is not being used.

**To Reproduce**
1. `flatpak install flathub dev.alextren.Spot`
2. `flatpak run dev.alextren.Spot`

**Expected behavior**
GTK theme is being used.

**Screenshots**
![Screenshot from 2021-02-25 01-17-52](https://user-images.githubusercontent.com/548843/109039281-90a2d900-7707-11eb-8757-5fe804dc3b6e.png)

**General information:**
 - Distribution: Manjaro
 - Installation method: installed from Flathub
 - Version: 0.1.8
 - Device used: desktop

**Stack trace:**
N/A

**Additional context**
N/A

**Comment by xou816** [comment] 2021-02-24 18:48
Hi! :) This is not a bug, Flatpak requires that themes be installed for flatpak as well. In your case, you'll have to install org.gtk.Gtk3theme.Matcha-sea. Hope this helps!

**Comment by teohhanhui** [comment] 2021-02-25 07:53
Please reopen this. That theme is already installed, but it's not being used.

**Comment by teohhanhui** [comment] 2021-02-25 07:59
> For the DConf option to work on Wayland the application must also be configured to have DConf access.

https://docs.flatpak.org/en/latest/desktop-integration.html#applying-themes

**Comment by teohhanhui** [comment] 2021-02-25 08:15
Hmm... Looks like there's no `org.gtk.Gtk3theme.Matcha-dark-sea` available.

 I'm curious what's different in @kleinHeiti's case (as seen in #69)? Are you using X11?

**Comment by teohhanhui** [comment] 2021-02-25 08:20
For some reason:

```
$ flatpak run --command=gtk-query-settings dev.alextren.Spot | grep dark
                     gtk-theme-name: "Matcha-dark-sea"
  gtk-application-prefer-dark-theme: FALSE
  ```

**Comment by kleinHeiti** [comment] 2021-02-25 08:21
Hello,
no, I have a Wayland session. Yesterday also came the update for the Flatpak GTK theme (see #69). How did you install the theme? I used this command:

flatpak install flathub org.gtk.Gtk3theme.matcha

**Comment by kleinHeiti** [comment] 2021-02-25 08:27
Ah, I see the problem: the Matcha-sea-Theme is not available as a dark variant:
```
Similar refs found for ‘org.gtk.Gtk3theme.matcha’ in remote ‘flathub’ (system):

   1) runtime/org.gtk.Gtk3theme.Matcha-dark-azul/x86_64/3.36
   2) runtime/org.gtk.Gtk3theme.Matcha-sea/x86_64/3.22
```
Maybe you have to use Matcha-dark-azul

**Comment by teohhanhui** [comment] 2021-02-25 08:32
@kleinHeiti But in #69 you mentioned you're using Matcha-sea. Haha... So I thought it worked for you.

**Comment by kleinHeiti** [comment] 2021-02-25 08:34
Ups - my fault. Sorry

**Comment by teohhanhui** [comment] 2021-02-25 08:40
https://github.com/vinceliuice/Matcha-gtk-theme/issues/143

**Comment by teohhanhui** [comment] 2021-02-25 08:55
Workaround for now:

    $ flatpak override --env=GTK_THEME=Matcha-sea:dark --user

**Comment by xou816** [comment] 2021-02-25 09:04
Thank you for your investigations!

**Comment by xou816** [comment] 2021-02-25 20:29
Can we close this? :) @teohhanhui

**Closed** 2021-02-26 10:19 UTC
Labels: bug
