### ISSUE TITLE
Two close buttons on elementaryOS

### ISSUE THREAD

**Issue by AnElementaryUser** [xou816/spot#432] opened 2022-01-14 14:00 UTC
**Describe the bug**
Two close buttons on elementaryOS

**Screenshots**
![Screenshot from 2022-01-14 16 54 43](https://user-images.githubusercontent.com/97615709/149621437-be9e4ad2-d668-42c5-b69e-ca269ac40474.png)

**General information:**
 - Distribution: elementaryOS 6.1
 - Installation method: Flathub
 - Version: 0.3
 - Device used: Desktop

**Additional context**
I think [these](https://github.com/lainsce/notejot/issues/340) are related.

**Comment by jannuary** [comment] 2022-01-14 14:13
Duplicate of #381.

**Comment by AnElementaryUser** [comment] 2022-01-14 14:18
@jannuary 

It is both duplicate and not 😃️ because it wasn't the case until I installed the latest release, so I thought the new version broke something and opened this issue but of course feel free to close it. You can see [here](https://github.com/xou816/spot/issues/424) that it was fine before. 🙂️

**Comment by yavko** [comment] 2022-01-14 20:13
> @jannuary
> 
> It is both duplicate and not smiley because it wasn't the case until I installed the latest release, so I thought the new version broke something and opened this issue but of course feel free to close it. You can see [here](https://github.com/xou816/spot/issues/424) that it was fine before. slightly_smiling_face

same
![image](https://user-images.githubusercontent.com/15178513/149579123-0fc34bb3-44cf-4d4e-9c25-45b250604d57.png)

**Comment by alissonlauffer** [comment] 2022-01-15 01:24
> because it wasn't the case until I installed the latest release

Though my report was made using the latest development release (between versions 0.2.2 and 0.3.0). I was unable to reproduce it in 0.2.2 either, so this is the same issue as mine.

**Comment by yavko** [comment] 2022-01-15 01:26
> > because it wasn't the case until I installed the latest release
> 
> Though my report was made using the latest development release (between versions 0.2.2 and 0.3.0). I was unable to reproduce it in 0.2.2 either, so this is the same issue as mine.

The new version looks like it uses libadwaita more, maybe its that, or maybe its because of the improved mobile layout.

**Comment by yavko** [comment] 2022-01-15 01:27
This issue is probably with gtk themes that aren't upstream adwaita

**Comment by jannuary** [comment] 2022-01-15 04:43
> This issue is probably with gtk themes that aren't upstream adwaita

No, it wouldn't be - "themes" don't have anything to do with it. Though I do wonder what's happening in the screenshot from the issue

**Comment by yavko** [comment] 2022-01-15 06:19
> > This issue is probably with gtk themes that aren't upstream adwaita
> 
> No, it wouldn't be - "themes" don't have anything to do with it. Though I do wonder what's happening in the screenshot from the issue

Oh actually that makes no sense, maybe just because i have my window controls to be on the left.

**Comment by AnElementaryUser** [comment] 2022-01-15 12:12
It is not about themes, it is actually about apps that utilizes multiple titlebars with libadwaita and/or GTK4; at least on elementary. That is why I mentioned [this](https://github.com/lainsce/notejot/issues/340#issue-1078697210)

**Comment by xou816** [comment] 2022-01-15 15:06
Right, thanks for mentioning notejot! The flathub version still has the same issue we have, I don't know if they've been able to fix it but that seems complicated at the moment

**Comment by jannuary** [comment] 2022-01-15 16:04
I think it we could just bind show-end-title-buttons of the secondary headerbar to the leaflet's folding state?

**Comment by xou816** [comment] 2022-01-15 18:04
Nah it's not that simple unfortunately, I gave some details in the original issue

**Comment by AnElementaryUser** [comment] 2022-01-15 18:46
> the original issue
Should we close this one?

**Comment by yavko** [comment] 2022-01-15 18:47
> > the original issue
> 
> Should we close this one?

The original one was happening in older versions, this only happens for me in newest, so they might need different solutions.

**Comment by xou816** [comment] 2022-01-15 20:08
The issue was on an unreleased dev version but it's definitely the same :) I'll close one of the two

**Comment by xou816** [comment] 2022-01-15 20:08
Discussion moved to #381

**Closed** 2022-01-15 20:08 UTC
Labels: bug, duplicate
