### ISSUE TITLE
two close buttons in split header bar

### ISSUE THREAD

**Issue by camelCaseNick** [xou816/spot#482] opened 2022-03-12 23:09 UTC
**Describe the bug**
The header bar is split into two when the window width is large enough to allow for this. When the window button layout is set to have them on the left side, the split header bar contains those buttons twice, once for each part.

**To Reproduce**
1. set close button to appear on the left side, e.g., run `gsettings set org.gnome.desktop.wm.preferences button-layout 'close:'`
2. open Spot
3. See two close buttons in split header bar

**Expected behavior**
I would expect seeing a single close button on the left side of the left part of the split header bar, but still having one when the sidebar is collapsed due to smaller window width.

**Screenshots**
![screenshot with the current behavior](https://user-images.githubusercontent.com/2989008/158038079-56c789cf-fe15-48d6-ba9e-9e8458932fef.png)

**General information:**
 - Distribution: Debian 11 with Gnome 3.38
 - Installation method [e.g. built from source, installed from Flathub...]: flatpak from Flathub
 - Version [e.g. 0.1.0]: 0.3.1
 - Device used [e. g. desktop, phone...]: desktop

**Comment by jannuary** [comment] 2022-03-13 03:57
Still dupe of #381 :)

**Comment by xou816** [comment] 2022-03-13 15:14
Beat me to it ahah thanks!

**Closed** 2022-03-13 16:23 UTC
Labels: bug, duplicate
