### ISSUE TITLE
Enable search for songs

### ISSUE THREAD

**Issue by Daria-E** [xou816/spot#703] opened 2024-02-17 11:20 UTC
**Describe the bug**
Currently, search only works for albums and artists. It should work for songs too.

**To Reproduce**
1. Search for any song.
2. See results load only for albums and artists.

**Expected behavior**
A separate category for songs should load, and show results.

**General information:**
 - Distribution: Fedora 39
 - Installation method: Installed from Flathub.
 - Version: 0.4.0
 - Device used: Laptop

**Additional context**
This is pretty much the only essential (IMO) feature left for me to use Spot daily. I could try adding it myself, but I'd need some pointers.

**Comment by ondras12345** [comment] 2024-02-17 11:51
Duplicate of https://github.com/xou816/spot/issues/35

**Comment by Diegovsky** [comment] 2024-04-10 00:01
This hurts a lot and is a very needed feature. Ill be closing as a duplicate but thank you for taking the time!

**Closed as completed by Diegovsky** 2024-04-10 00:01 UTC
Labels: bug
